language: node_js
node_js:
- 7.8.0
script:
- yarn test
- yarn build:all
after_success:
- echo "Build successful; Ready to deploy"
notifications:
  email: false
  slack:
    secure: ClVnVgYhd8qcozxKOnv0ARo5oSgJwOlXv2Bbh9WhEP3H3sn5kAB+UDVUNoCJmqdTbW3JBHrrQjz9wrYTSdOilet2FxU5r5xIMdoMWhp9SKFmaZeqLb3NWTGD+PejPK1upDCwkeqyjk/g3cotc6FJADv6VJQEsYTxycxzqb+/Z45TQfUA58d/8Bz85XREmiONZyP1HojwFPgchF/+rKpKFU9/gBXmrfRpBEvygfcxjThcspYS4V/fKCDQeGgegkTkCEWQZHX+JggL2WbuvSxOS15PrUftlZNiJTZ5jWh0YbJMF5EGIDZJEuERfnKBUNIWPGRzRozGqy7hQUMtMTp7LEGX9prR1nNwVGjdT6reEu+Hb85gLE8ZITF7FmW1AhtQLSNuMAxB4o8NQZDAKOoAcJOMnIlu+w3kbzEYmLEtBVucTr1wzCrxE3adlTxOSrhe2eoyi4uzKW9qp2F+AQ5eNYvu0naz0CtkufGa5vsrkaMUP3r6WuX4+RWUSJJiKBGzhVou3wD1blBRwysZWYB4tu+b1OCxTEop7XjaFTWsXxWGgJvS57bdYDQyLLG7EV+teLOLI9nIPzFj+l0dmh8FDE2Q8CpAepM3crZkiIIvIXVLgIFe+Jekm/ImOilRck9WAC1GKK4mQPb3lXdmrWnddt8i7bochn3MjkwovZnytRY=
deploy:
  provider: heroku
  api_key:
    secure: K49rkVlo6Wxr50UaTDHMRhQkFENRFsmHSA5dBuOgkQ1a/le+ChcmwL3KNCOWVdyCfFuj0Y/Mqhp9/7u2SOOOjGsBuMZLHMH2VCCmjRoHfUk4hW1thU7qmON6oQDDBIuxgUzECCfNFkk0fH5C4xhvFAdR2EEc8Vs1uhK774PR+BCx/DBS1knQ+RId6ybKrg87XetBr7eBJJxD0X9AW7MQ1RsY7DSF+hVbJ9UoTQSdVZJIL6FsLmy30CnNNSmbCYNzTBv0gkNh23PWbnWsPrtfftk+J4NwDo4l4hx0tgdHqHw6dRI80gYelrkW4P+MnBld6FHL6X/3Uc1jmx8+AKIUUF+YZvA/brVnlXiBHP+63r/miPp5Zdr+PYB83ZpWGz6G2zvygKDm/Nv9zydHrGwLTTuKBgG7GTfRYvLoBZ9GYIYdH6DZr50sYiSzOdt/+MvCRuh0qH3E+izWlIEYQEM7N6T481LKf2WSEBN+cxZPFCgjttKnhrnD44ldH0xILVMrNu16rvMmWB7H6/oPXDbJIvAHBOOmuefHW0ri0JUInqaQl3TKbL29iJKfHtfBmwJG/50OpLbNvr8AAYdYESLvi9FrYhtUloQOm1M1Ilmlm6gg3QDTPLmjpBmZWoNyxCZbzAaAvql0JuoHBFalTab1Is2j/ceML1/9KQwVD02FtN8=
  app: d4sd-staging
  on:
    repo: creativecolab/civicchallenge-frontend
    branch: dev
