language: node_js

node_js:
- 7

notifications:
  email: false
  slack:
    secure: ClVnVgYhd8qcozxKOnv0ARo5oSgJwOlXv2Bbh9WhEP3H3sn5kAB+UDVUNoCJmqdTbW3JBHrrQjz9wrYTSdOilet2FxU5r5xIMdoMWhp9SKFmaZeqLb3NWTGD+PejPK1upDCwkeqyjk/g3cotc6FJADv6VJQEsYTxycxzqb+/Z45TQfUA58d/8Bz85XREmiONZyP1HojwFPgchF/+rKpKFU9/gBXmrfRpBEvygfcxjThcspYS4V/fKCDQeGgegkTkCEWQZHX+JggL2WbuvSxOS15PrUftlZNiJTZ5jWh0YbJMF5EGIDZJEuERfnKBUNIWPGRzRozGqy7hQUMtMTp7LEGX9prR1nNwVGjdT6reEu+Hb85gLE8ZITF7FmW1AhtQLSNuMAxB4o8NQZDAKOoAcJOMnIlu+w3kbzEYmLEtBVucTr1wzCrxE3adlTxOSrhe2eoyi4uzKW9qp2F+AQ5eNYvu0naz0CtkufGa5vsrkaMUP3r6WuX4+RWUSJJiKBGzhVou3wD1blBRwysZWYB4tu+b1OCxTEop7XjaFTWsXxWGgJvS57bdYDQyLLG7EV+teLOLI9nIPzFj+l0dmh8FDE2Q8CpAepM3crZkiIIvIXVLgIFe+Jekm/ImOilRck9WAC1GKK4mQPb3lXdmrWnddt8i7bochn3MjkwovZnytRY=
