language: node_js
node_js:
- 7.8.0
script:
- yarn test
- yarn build:all
after_success:
- echo "Build successful; Ready to deploy"
notifications:
  email: false
  slack:
    secure: ClVnVgYhd8qcozxKOnv0ARo5oSgJwOlXv2Bbh9WhEP3H3sn5kAB+UDVUNoCJmqdTbW3JBHrrQjz9wrYTSdOilet2FxU5r5xIMdoMWhp9SKFmaZeqLb3NWTGD+PejPK1upDCwkeqyjk/g3cotc6FJADv6VJQEsYTxycxzqb+/Z45TQfUA58d/8Bz85XREmiONZyP1HojwFPgchF/+rKpKFU9/gBXmrfRpBEvygfcxjThcspYS4V/fKCDQeGgegkTkCEWQZHX+JggL2WbuvSxOS15PrUftlZNiJTZ5jWh0YbJMF5EGIDZJEuERfnKBUNIWPGRzRozGqy7hQUMtMTp7LEGX9prR1nNwVGjdT6reEu+Hb85gLE8ZITF7FmW1AhtQLSNuMAxB4o8NQZDAKOoAcJOMnIlu+w3kbzEYmLEtBVucTr1wzCrxE3adlTxOSrhe2eoyi4uzKW9qp2F+AQ5eNYvu0naz0CtkufGa5vsrkaMUP3r6WuX4+RWUSJJiKBGzhVou3wD1blBRwysZWYB4tu+b1OCxTEop7XjaFTWsXxWGgJvS57bdYDQyLLG7EV+teLOLI9nIPzFj+l0dmh8FDE2Q8CpAepM3crZkiIIvIXVLgIFe+Jekm/ImOilRck9WAC1GKK4mQPb3lXdmrWnddt8i7bochn3MjkwovZnytRY=
deploy:
  provider: heroku
  api_key:
    secure: NeoEY5yZryQ46hG0Hj7wvdSYDlRF6y8DHJb3y02i4gQc4u9WpgnoM1u4fhOu3QDWYNoSzRac+apvHxFNoRQu9k6j/UTZqZppzv3okG50eBou9Xswo7DWYUT7sAn13qwpF1LW3iTqn6/nQtcZw2TC0LA4r9ndTbVirAS6YONVHCklo+SWsekp5+EEZCUnhotJRNfnnGcGj1Y2bP9Tg1tUGQJaXFL+RDyEbsAsG7doHesOD7tOt8dnrOKRkZUnE4LdFwkvO+puQvj/8f2TkbeaUXIx2RUu/3AOCGnbtLcrH/PolwU2Vqka9ItbrLaFTZWhdINDoRRGNjcGJZ+boys9853hy7dBQyQTfzLTgmg5onfkYVqEOtUFtKUTZW5ojohne+GFd8SmQlGEYkBi8lDZlp2ALRoQteqW2vZ1DxHIKmURPFokVJBlwQ+Q/n2qJQSBrR28v+2a9GlS+1UgT5P/p6JgRCBwduxWwxMVC5cyzQbJV85QcMWPptFSw6QhTVxeks99gmPuw+Zk6+eZNujUc/ot7d81inn1mx8FvbDqtBnArFEVc8o+ySf6EjEKgc4ZYPy7vpG9LbcXKfwhzPftVDOBw87xoR+6B437X5ylyxnTRe7sDWeDCMs1C1PtsgNJel9YXknhqjeScnkxHZAz7y65e6nZhL2h9IY9IunQ6Co=
  app: d4sd-staging
  on:
    condition: "$TRAVIS_BRANCH = dev"
    repo: davidcluu/civicchallenge-frontend
    branch: dev
